[tool.basedpyright]
extraPaths = ["lib/python"]
executionEnvironments = [{ root = "scripts" }]
reportAny = false
reportExplicitAny = false
reportMissingTypeStubs = false
reportUnusedCallResult = false

[tool.ruff]
src = ["scripts"]
